Dimensões D1, D2 e D3

In [4]:
import numpy as np


In [5]:
# Array 1D:

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [6]:
d1.shape
# 3, significa 1D

(3,)

In [7]:
# Número de dimensões
d1.ndim

1

In [8]:
d1.dtype

dtype('int32')

In [9]:
d2 = np.array([[1,2,3], [4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [10]:
d2.shape,


((2, 3),)

In [11]:
d2.ndim


2

In [12]:
d2.dtype

dtype('int32')

D3:

In [13]:
d3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(d3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
d3.shape

(2, 2, 3)

In [15]:
d3.ndim

3

In [17]:
d3.dtype

dtype('int32')