In [3]:
import numpy as np

a = np.array([[2,3,4,5], [6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [5]:
# Selecionar o número 8, array[row, colum] 
a[1,2]

8

In [6]:
a[1,-2]

8

In [9]:
# Selecionar 7
a[1,3]

7

In [10]:
a[1,-3]


7

In [12]:
a[0,:]

array([2, 3, 4, 5])

In [13]:
a[1,:]

array([6, 7, 8, 9])

In [14]:
a[:,1]

array([3, 7])