Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8]). 

In [1]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 


In [2]:
desvio_padrão = np.std(tempos_ciclo)
print(desvio_padrão)

0.592546294487706


In [3]:
print(np.where(tempos_ciclo > 5))

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [4]:
condição = tempos_ciclo > 5
print(np.where(condição))

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [5]:
condição = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
anomalias = np.where(condição)
print(anomalias)

(array([7], dtype=int64),)


In [6]:
print(tempos_ciclo[anomalias])

[7.2]


In [7]:
print(tempos_ciclo[condição])

[7.2]


In [8]:
print(f'Os tempos que estão nas condições pedidias são {tempos_ciclo[condição]}.')

Os tempos que estão nas condições pedidias são [7.2].


BONUS 1:

In [9]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
print(media)

5.8


In [10]:
desvio_padrão = np.std(tempos_ciclo)
print(desvio_padrão)

0.592546294487706


In [11]:
condição = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
anomalias = np.where(condição)
print(condição)

[False False False False False False False  True False]


In [12]:
contrário_condição = (tempos_ciclo <= media + 2 * desvio_padrão) & (tempos_ciclo >= media - 2 * desvio_padrão)
print(np.where(contrário_condição))

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [13]:
print(np.where(~condição))

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [14]:
print(~condição)

[ True  True  True  True  True  True  True False  True]


In [15]:
print(not False)
print(not True)

True
False


### Bônus 2

In [17]:

rng = np.random.default_rng(seed=0)
tempos_gerados = rng.normal(loc=media, scale= desvio_padrao, size=100)
print(tempos_gerados)

NameError: name 'desvio_padrao' is not defined

In [18]:
print(media)
print(tempos_gerados.mean())

5.8


NameError: name 'tempos_gerados' is not defined