Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8]). 

In [1]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 


In [2]:
desvio_padrão = np.std(tempos_ciclo)
print(desvio_padrão)

0.592546294487706


In [3]:
print(np.where(tempos_ciclo > 5))

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [4]:
condição = tempos_ciclo > 5
print(np.where(condição))

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [5]:
condição = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
anomalias = np.where(condição)
print(anomalias)

(array([7], dtype=int64),)


In [6]:
print(tempos_ciclo[anomalias])

[7.2]


In [7]:
print(tempos_ciclo[condição])

[7.2]


In [8]:
print(f'Os tempos que estão nas condições pedidias são {tempos_ciclo[condição]}.')

Os tempos que estão nas condições pedidias são [7.2].


BONUS 1:

In [9]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
print(media)

5.8


In [10]:
desvio_padrão = np.std(tempos_ciclo)
print(desvio_padrão)

0.592546294487706


In [11]:
condição = (tempos_ciclo > media + 2 * desvio_padrão) | (tempos_ciclo < media - 2 * desvio_padrão)
anomalias = np.where(condição)
print(condição)

[False False False False False False False  True False]


In [12]:
contrário_condição = (tempos_ciclo <= media + 2 * desvio_padrão) & (tempos_ciclo >= media - 2 * desvio_padrão)
print(np.where(contrário_condição))

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [13]:
print(np.where(~condição))

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)


In [14]:
print(~condição)

[ True  True  True  True  True  True  True False  True]


In [15]:
print(not False)
print(not True)

True
False


### Bônus 2

In [16]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
print(media)

5.8


In [17]:

import numpy as np

rng = np.random.default_rng(seed=42)
tempos_gerados = rng.normal(loc=media, scale= desvio_padrão, size=100)
print(tempos_gerados)

[5.98055898 5.18376127 6.24467708 6.35732814 4.64392133 5.02839836
 5.87575136 5.61261162 5.79004454 5.29453198 6.32108401 6.26087773
 5.83912625 6.4679426  6.07702093 5.29082944 6.01850191 5.23181767
 6.32052247 5.77041659 5.69046049 5.39651772 6.52441234 5.70843413
 5.54619594 5.59134457 6.11541784 6.01654253 6.04456318 6.05528139
 7.06902535 5.55918029 5.49647247 5.31780199 6.16499632 6.46896835
 5.73248086 5.30216839 5.31145671 6.18550635 6.24041251 6.12184405
 5.40565469 5.93756633 5.86914174 5.92958312 6.31636189 5.93249071
 6.20228772 5.84004373 5.97131663 6.1740675  4.93656772 5.61058001
 5.52128243 5.4214353  5.63696548 6.68582193 5.28695498 6.37374975
 4.80282175 5.60156512 5.89643873 6.14736387 6.22143467 6.27009496
 5.59336425 5.52603516 6.30839043 5.68664333 5.0440968  5.12847486
 5.25518195 6.09459076 5.88439384 6.20914454 5.54683303 5.89394211
 6.17069127 5.61669785 6.07066047 5.40777824 5.58487379 5.57380263
 5.09140965 6.08855374 5.52185738 5.80740334 6.08486465 6.0645

In [18]:
print(media)
print(tempos_gerados.mean())

5.8
5.7702129279899035
