# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função np.where() é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.



In [1]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)


3714.285714285714


# Identificar funcionários com salários acima da média
funcionários_acima_da_media = np.where(salarios > media_salarial)
print(funcionários_acima_da_media)

In [2]:
# Identificar funcionários com salários acima da média

funcionários_acima_da_media = np.where(salarios > media_salarial)
print(funcionários_acima_da_media)

(array([2, 4, 5, 6], dtype=int64),)


In [3]:
# Filtrando: 

print(salarios[funcionários_acima_da_media])

[4000 4500 4000 5000]


In [4]:
# Posso fazer direto sem usar o np.where:

print(salarios[salarios > media_salarial])


[4000 4500 4000 5000]


In [5]:
print(salarios[salarios < 4000])

print(salarios [salarios <= 4000])

print(salarios [salarios <= 6000])

print(salarios [salarios >= 6000])


[3000 3500 2000]
[3000 3500 4000 2000 4000]
[3000 3500 4000 2000 4500 4000 5000]
[]


In [6]:
# dar bônus de 10% para os funcionários com salários abaixo da média

print(np.where(salarios > media_salarial, 'Acima da média.', 'Abaixo da média.'))

['Abaixo da média.' 'Abaixo da média.' 'Acima da média.'
 'Abaixo da média.' 'Acima da média.' 'Acima da média.' 'Acima da média.']


In [7]:
salario_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)
print(salarios)
print(salario_bonus)


[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]
