# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.

## Instalação

Para instalar o NumPy, você pode usar o pip, que é o gerenciador de pacotes do Python.

```python
pip install numpy


## Arrays

Um array é uma estrutura de dados que armazena valores do mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes. Vamos criar um array.

In [2]:
# Criação de um array

import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)


[1 2 3 4 5]


In [3]:
print(array[0])

1


In [5]:
print(array[1:4])

[2 3 4]


In [4]:
print(array[0:-1])


[1 2 3 4]


In [6]:
print(array[0:-1:2])

[1 3]


In [7]:
print(array[0::2])

[1 3 5]


In [8]:

print(array[::2])

[1 3 5]


In [9]:
print(array[::])

[1 2 3 4 5]


In [10]:
print(array[::-1])

[5 4 3 2 1]


## Aplicações do dia a dia

Vamos supor que você trabalha em uma empresa de vendas e tem os preços de diferentes produtos em uma lista. Você quer aumentar o preço de todos os produtos em 10%. Com NumPy, isso é simples.


In [11]:
import numpy as np

# Preços dos produtos
precos = np.array([20, 25, 30, 35, 40])

# Aumentar os preços em 10 % (ex.: ajuste de inflação)
novos_precos = precos * 1.10
print(novos_precos)


[22.  27.5 33.  38.5 44. ]


## np.sum()

NumPy vem com muitas funções úteis. Por exemplo, você pode usar a função `sum()` para somar todos os elementos de um array. Isso pode ser útil para somar todas as vendas de um dia, por exemplo.

In [13]:
import numpy as np

# Vendas do dia
vendas = np.array([200, 220, 250, 210, 300])

# Somar todas as vendas
total_vendas = np.sum(vendas)
print(total_vendas)

1180


## np.mean()

A função `mean()` é usada para calcular a média de um array. Por exemplo, se você quiser calcular a média de vendas diárias em uma semana.


In [14]:
import numpy as np

# Vendas diárias em uma semana
vendas = np.array([200, 220, 250, 210, 300, 280, 230])

# Calcular a média de vendas
media_vendas = np.mean(vendas)
print(media_vendas)


241.42857142857142
